###### 2021-01-30

## 1. Tensor
    - numpy의 array와 사용법이 유사하다

In [5]:
import torch
import numpy as np


In [6]:
x = torch.empty(5, 4)
print(x)

tensor([[3.3741e-35, 0.0000e+00, 7.0065e-44, 6.8664e-44],
        [6.3058e-44, 6.7262e-44, 6.8664e-44, 6.3058e-44],
        [7.1466e-44, 6.7262e-44, 1.1771e-43, 6.8664e-44],
        [6.8664e-44, 8.1275e-44, 7.1466e-44, 7.1466e-44],
        [8.1275e-44, 7.0065e-44, 6.7262e-44, 6.4460e-44]])


In [7]:
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# 임의의 난수를 가지는 tensor생상
torch.rand(5, 6)

tensor([[0.4505, 0.5622, 0.4359, 0.1207, 0.8722, 0.0659],
        [0.5945, 0.3082, 0.1778, 0.7011, 0.5990, 0.7943],
        [0.7590, 0.7719, 0.8455, 0.6526, 0.9826, 0.6863],
        [0.8873, 0.5875, 0.4392, 0.0966, 0.9616, 0.0969],
        [0.5722, 0.4879, 0.1360, 0.5262, 0.3183, 0.9374]])

In [11]:
## 리스트 또는 array를 텐서로 변한
## np.array() 하는것처럼 torch.tensor() 사용하면되


l = [13, 4]
r = np.array([4, 56, 7])

torch.tensor(l)
torch.tensor(r)

tensor([ 4, 56,  7])

In [15]:

x = torch.rand(2, 2)
y = torch.rand(2, 2)


## 텐서 사이즈알아보가
x.size()

torch.Size([2, 2])

In [14]:
## 텐서타입
type(x)

torch.Tensor

In [20]:
## 텐서 더하는 방법
print(x + y)
print(x.add(y))
print(y.add(x))

tensor([[0.9722, 1.2320],
        [0.2028, 0.8612]])
tensor([[0.9722, 1.2320],
        [0.2028, 0.8612]])
tensor([[0.9722, 1.2320],
        [0.2028, 0.8612]])


In [22]:
## 더하는 방법인데.. 판다스의 inplace=True처럼 더해주는것
y.add_(x)
print(y)

tensor([[1.6943, 2.1747],
        [0.2747, 1.6530]])


In [25]:
## 텐서의 원소에 접근하는 방법
## 판다스와 넘파이와 같이 접근하면된다
print(x[1, 1])
print(x[:, 1])

tensor(0.7918)
tensor([0.9427, 0.7918])


In [34]:
x = torch.rand(8, 8)
print(x)
## numpy의 reshape와 같은기능 : view
## Fully Connected Layer로 텐서를 전달할떄, 텐서를 1차원으로 만들어서 넘겨주는데 그떄 사용한다.
print(x.view(64))
print(x.view(-1, 16)) 

tensor([[0.8333, 0.8490, 0.1015, 0.3951, 0.2383, 0.3128, 0.8162, 0.9273],
        [0.6860, 0.6464, 0.6527, 0.4853, 0.0962, 0.2695, 0.8146, 0.4713],
        [0.1290, 0.8681, 0.2828, 0.1516, 0.2508, 0.0297, 0.7028, 0.7227],
        [0.9620, 0.2514, 0.7127, 0.3437, 0.0841, 0.6919, 0.4685, 0.5547],
        [0.3305, 0.8759, 0.8030, 0.2840, 0.0126, 0.9466, 0.5968, 0.7912],
        [0.5526, 0.6325, 0.8800, 0.3675, 0.9538, 0.1242, 0.4736, 0.2668],
        [0.0714, 0.8680, 0.5995, 0.7133, 0.7154, 0.7135, 0.2543, 0.8898],
        [0.1141, 0.7681, 0.4683, 0.9159, 0.6620, 0.5822, 0.8241, 0.4858]])
tensor([0.8333, 0.8490, 0.1015, 0.3951, 0.2383, 0.3128, 0.8162, 0.9273, 0.6860,
        0.6464, 0.6527, 0.4853, 0.0962, 0.2695, 0.8146, 0.4713, 0.1290, 0.8681,
        0.2828, 0.1516, 0.2508, 0.0297, 0.7028, 0.7227, 0.9620, 0.2514, 0.7127,
        0.3437, 0.0841, 0.6919, 0.4685, 0.5547, 0.3305, 0.8759, 0.8030, 0.2840,
        0.0126, 0.9466, 0.5968, 0.7912, 0.5526, 0.6325, 0.8800, 0.3675, 0.9538,
       

In [36]:
## tensor를 numpy로 변환하는 방법
y = x.numpy()
print(y)
print(type(y))

[[0.8332532  0.8490366  0.10153574 0.39505762 0.23829323 0.31277543
  0.8161934  0.92732006]
 [0.68601227 0.64643764 0.65270233 0.4853074  0.0961861  0.269495
  0.81459457 0.47132248]
 [0.12897879 0.8680842  0.28284234 0.1516434  0.2507667  0.02972382
  0.7028391  0.7226516 ]
 [0.9619718  0.25135887 0.71266377 0.34370315 0.08413011 0.69186515
  0.46846396 0.5547087 ]
 [0.33046097 0.8758634  0.8030369  0.28395838 0.01256222 0.9466464
  0.59682983 0.7912494 ]
 [0.5526447  0.6325314  0.8799503  0.36746132 0.95382243 0.12418842
  0.47363275 0.26679337]
 [0.07140428 0.86800545 0.5995056  0.713274   0.7153813  0.7134586
  0.2543428  0.88976705]
 [0.11408556 0.76807165 0.46826178 0.91593957 0.6619573  0.5822325
  0.82411665 0.48580474]]
<class 'numpy.ndarray'>


In [40]:
## 텐서의 원소를 텐서가아닌 값(Value : 스칼라)로 출력할떄
print(x[1, 1].item())
print(x[1, 1])

0.6464376449584961
tensor(0.6464)
