## 2. 역전파

In [2]:
import torch

### 딥러닝 구조의 흐름

#### (1) 변수 선연 (데이터입력)

(requires_grad = True)
아래를 보면 텐서하나를 만들어 `x`에 할당했다. 그 중 (requires_grad = True)라는 옵션은 `x`에 관한 연산들을 모두 추적할 수 있도록 해주는 옵션이다.
연산을 추적하여 미분을 진행한다.

In [15]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


#### (2) 모델내 연산 예측값 산출

In [16]:
y = x + 1
print(y)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


#### (3) 손실함수 계산 및 손실 산출

In [19]:
z = 2*y**2
res = z.mean()
print(res)

tensor(8., grad_fn=<MeanBackward0>)


In [21]:
## 위에서 구한 연산을 기점으로 미분을 하는데 역전파를 하겟다
res.backward()

In [22]:
print(x.grad)

tensor([[2., 2.],
        [2., 2.]])


## Torch.nn
    - 일반적으로 위처럼 변수를 일일히 지정해주지 않아도 된다.
    - Torch.nn을 사용하면 사람들이 미리 구현해놓은 (CNN 등) 신경망 모델을 사용하기만 하면된다!

In [ ]:
import torch.nn as nn
import torch.nn.functional as F